site_name: HEAT - Heterogeneous Embedded Acceleration Toulouse
site_description: HEAT - The Embedded Research Hub.
site_url: https://toulouse-embedded-accel.github.io/HEAT/
repo_url: https://github.com/Toulouse-Embedded-Accel/HEAT
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette: 
    # Light theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.sections

nav:
  - Welcome to HEAT: index.md
  - 🚀 Quickstarts & Setup: quickstarts/
  - 🛠️ Field Notes (REX): rex/
  - 🔬 Projects & Code: projects.md
  - 📚 Talks & Resources: talks.md
  - 👥 Community Directory: directory.md

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
